#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamDroid.FitChart.Sample.Resource", IsApplication=true)]

namespace XamDroid.FitChart.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.frankcalise.widgets.Resource.Attribute.animationMode = global::XamDroid.FitChart.Sample.Resource.Attribute.animationMode;
			global::com.frankcalise.widgets.Resource.Attribute.backStrokeColor = global::XamDroid.FitChart.Sample.Resource.Attribute.backStrokeColor;
			global::com.frankcalise.widgets.Resource.Attribute.strokeSize = global::XamDroid.FitChart.Sample.Resource.Attribute.strokeSize;
			global::com.frankcalise.widgets.Resource.Attribute.valueStrokeColor = global::XamDroid.FitChart.Sample.Resource.Attribute.valueStrokeColor;
			global::com.frankcalise.widgets.Resource.Color.default_back_color = global::XamDroid.FitChart.Sample.Resource.Color.default_back_color;
			global::com.frankcalise.widgets.Resource.Color.default_back_stroke_color = global::XamDroid.FitChart.Sample.Resource.Color.default_back_stroke_color;
			global::com.frankcalise.widgets.Resource.Color.default_chart_value_color = global::XamDroid.FitChart.Sample.Resource.Color.default_chart_value_color;
			global::com.frankcalise.widgets.Resource.Dimension.default_stroke_size = global::XamDroid.FitChart.Sample.Resource.Dimension.default_stroke_size;
			global::com.frankcalise.widgets.Resource.Id.linear = global::XamDroid.FitChart.Sample.Resource.Id.linear;
			global::com.frankcalise.widgets.Resource.Id.overdraw = global::XamDroid.FitChart.Sample.Resource.Id.overdraw;
			global::com.frankcalise.widgets.Resource.String.library_name = global::XamDroid.FitChart.Sample.Resource.String.library_name;
			global::com.frankcalise.widgets.Resource.Styleable.FitChart = global::XamDroid.FitChart.Sample.Resource.Styleable.FitChart;
			global::com.frankcalise.widgets.Resource.Styleable.FitChart_animationMode = global::XamDroid.FitChart.Sample.Resource.Styleable.FitChart_animationMode;
			global::com.frankcalise.widgets.Resource.Styleable.FitChart_backStrokeColor = global::XamDroid.FitChart.Sample.Resource.Styleable.FitChart_backStrokeColor;
			global::com.frankcalise.widgets.Resource.Styleable.FitChart_strokeSize = global::XamDroid.FitChart.Sample.Resource.Styleable.FitChart_strokeSize;
			global::com.frankcalise.widgets.Resource.Styleable.FitChart_valueStrokeColor = global::XamDroid.FitChart.Sample.Resource.Styleable.FitChart_valueStrokeColor;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int animationMode = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int backStrokeColor = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int strokeSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int valueStrokeColor = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int chart_value_1 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int chart_value_2 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int chart_value_3 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int chart_value_4 = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int default_back_color = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int default_back_stroke_color = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int default_chart_value_color = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int chart_size = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int default_stroke_size = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int stroke_size = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int AddButton = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int FitChart = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int linear = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int overdraw = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int chart_style = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FitChart = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 3
			public const int FitChart_animationMode = 3;
			
			// aapt resource value: 2
			public const int FitChart_backStrokeColor = 2;
			
			// aapt resource value: 0
			public const int FitChart_strokeSize = 0;
			
			// aapt resource value: 1
			public const int FitChart_valueStrokeColor = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
